name: Node CI

on:
  push:
    branches:
      - master
    tags:
      - release

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: test and publish
      run: |
        npm install -g standard-version nyc mocha typescript ts-node yarn
        npm ci
        yarn lint
        yarn test:integration
        nyc check-coverage --lines 95 --functions 95 --branches 88 --statements 95
        yarn coverage
        yarn build
        echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
        npm publish --access public
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}